# Generated by Django 4.2.11 on 2024-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=64)),
                ("phone_number", models.CharField(max_length=10)),
                (
                    "activity",
                    models.CharField(
                        choices=[("LN", "Lend"), ("BR", "Borrow")], max_length=2
                    ),
                ),
                ("college", models.CharField(max_length=128)),
                ("department", models.CharField(max_length=64)),
                ("semester", models.PositiveSmallIntegerField()),
                ("subject", models.CharField(max_length=128)),
                ("book_name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "mysite_enquiries",
            },
        ),
    ]
