# Generated by Django 4.2.11 on 2024-03-06 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="phone_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", message="Enter a valid 10-digit phone number."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="semester",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ]
            ),
        ),
    ]
